version: '3'

services:

  datasource:
    build:
      context: datasource/
      dockerfile: ../Dockerfile
      target: frankenstein-datasource
  
  datasource-py:
    build:
      context: datasource-py/
      dockerfile: ../Dockerfile
      target: frankenstein-datasource-py

  database:
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: frankenstein
