version: '3'

services:
  
  datasource-py:
    build:
      context: datasource-py/
      dockerfile: ../Dockerfile
      target: fs-datasource-py
    environment:
      CLIENT_ID_FILE: /run/secrets/reddit-client-id
      CLIENT_SECRET_FILE: /run/secrets/reddit-client-secret
    secrets:
      - reddit-client-id
      - reddit-client-secret
    
  kafka:
    image: bitnami/kafka:3.4.0
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeper:2181

  zookeper:
    image: zookeeper:3.8.1
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

secrets:
  reddit-client-id:
    file: secrets/reddit_client_id.txt
  reddit-client-secret:
    file: secrets/reddit_client_secret.txt
