version: '3'

services:

  # datasource:
  #   build:
  #     context: datasource-js/
  #     dockerfile: ../Dockerfile
  #     target: frankenstein-datasource
  
  datasource-py:
    build:
      context: datasource-py/
      dockerfile: ../Dockerfile
      target: frankenstein-datasource-py
    secrets:
      - frankenstein-secrets

  # database:
  #   image: postgres:14.1
  #   environment:
  #     POSTGRES_USER: postgres_admin
  #     POSTGRES_PASSWORD: postgres_password
  #     POSTGRES_DB: frankenstein

secrets:
  frankenstein-secrets:
    file: frankenstein-secrets.txt
