version: '3'

services:

  datasource-py:
    container_name: datasource-py
    build:
      context: datasource-py/
      dockerfile: ../Dockerfile
      target: fs-py-dependencies
    environment:
      CLIENT_ID_FILE: /run/secrets/reddit-client-id
      CLIENT_SECRET_FILE: /run/secrets/reddit-client-secret
    secrets:
      - reddit-client-id
      - reddit-client-secret
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v4.8.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.localhost`)"
      - "traefik.http.routers.dozzle.entrypoints=http"
  
  zookeper:
    container_name: zookeeper
    image: zookeeper:3.8.1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_4LW_COMMANDS_WHITELIST=*
    healthcheck:
      test: echo ruok | nc localhost 2181 || exit 1
      interval: 10s
      retries: 3
      start_period: 3s
      timeout: 2s
  
  # zoonavigator:
  #   container_name: zoonavigator
  #   image: elkozmon/zoonavigator:latest
  #   ports:
  #     - 3002:9000
  #   environment:
  #     AUTO_CONNECT_CONNECTION_STRING: zookeeper:2181

  kafka:
    container_name: kafka
    build:
      dockerfile: Dockerfile
      target: fs-kafka
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeper:2181
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 2s
    depends_on:
      zookeper:
        condition: service_healthy
  
  kafka-init:
    container_name: kafka-init
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      kafka:
        condition: service_healthy
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
               cub kafka-ready -b kafka:9092 1 30 && \
               kafka-topics --create --topic comments --if-not-exists --bootstrap-server kafka:9092'"
  
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 3001:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: frankenstein
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      LOGGING_LEVEL_COM_PROVECTUS: info
    depends_on:
      - kafka

secrets:
  reddit-client-id:
    file: secrets/reddit_client_id.txt
  reddit-client-secret:
    file: secrets/reddit_client_secret.txt
