version: '3'

services:

  # datasource:
  #   build:
  #     context: datasource-js/
  #     dockerfile: ../Dockerfile
  #     target: frankenstein-datasource
  
  datasource-py:
    build:
      context: datasource-py/
      dockerfile: ../Dockerfile
      target: fs-datasource-py
    environment:
      CLIENT_ID_FILE: /run/secrets/reddit-client-id
      CLIENT_SECRET_FILE: /run/secrets/reddit-client-secret
    secrets:
      - reddit-client-id
      - reddit-client-secret

  # database:
  #   image: postgres:14.1
  #   environment:
  #     POSTGRES_USER: postgres_admin
  #     POSTGRES_PASSWORD: postgres_password
  #     POSTGRES_DB: frankenstein

secrets:
  reddit-client-id:
    file: secrets/reddit_client_id.txt
  reddit-client-secret:
    file: secrets/reddit_client_secret.txt
