version: '3'

services:
    
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v4.8.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:8080
    labels:
      - VIRTUAL_HOST=dozzle.local
      - VIRTUAL_PORT=8001

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "3000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.local
      - VIRTUAL_PORT=8000
